name: 'Gitmoji Changelog'
description: 'Maintains a Changelog based on Commits in Gitmoji Convention. At the moment JS supported.'
author: 'Templum'

runs:
  using: 'node20'
  main: './action/index.js'

inputs:
  add-authors:
    default: 'true'
    description: 'This determines whether the Authors of the Commits should be added to the changelog. It should be a valid YAML boolean value (e.g. TRUE, FALSE, true, false).'
  override-project-path:
    default: ''
    description: 'This can be used to provide a relative path to the project root that should be used to collect history. Should not start with ".".'
  override-changelog-path:
    default: ''
    description: 'This can be used to provide a relative path to the project root where the CHANGELOG should be stored. It should end on "CHANGELOG.md" and not start with ".".

outputs:
  for-version:
    description: 'Will be populated with the version for which the CHANGELOG was generated.'
  changelog-path:
    description: 'The absolute path on the runner where the CHANGELOG.md is located.'

branding:
  icon: 'edit'
  color: 'blue'
