name: Branch Flow
on:
  push:
    paths-ignore:
      - "./action/**"
      - "./.devcontainer/**"
      - ".gitignore"
      - "LICENSE"
      - "README.md"
    branches:
      - "main"
      - "develop"
jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Check Lint
        run: npm run check:lint
      - name: Check Typescript
        run: npm run check:tsc
      - name: Run Unit Tests
        run: npm run test:unit