name: Maintain Compiled Action
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Compile Action
        run: npm run pack
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: maintain/action-update
          title: ":package: Updated compiled action with latest code"
          commit-message: ":package: Updated compiled action with latest code"
