name: Verify Pull Request
on: [pull_request]
permissions:
  pull-requests: write
jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Check Lint
        run: npm run check:lint
      - name: Check Typescript
        run: npm run check:tsc
      - name: NCC Build
        run: npm run build
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: npm
        continue-on-error: true
      
        